version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node

    branches:
      only:
        # Whitelist branches to build for.
        - master
    steps:
      # Checkout repo & subs:
      - checkout

      # Get npm cache:
      - restore_cache:
          key: npm

      # Build steps:
      - run: npm install
      - run: npm run build

      # Make fast:
      - save_cache:
          key: npm
          paths:
            - ~/.npm

      # Run the deploy:
      - deploy:
          command: .circleci/deploy.sh
